# Generated by Django 4.2.21 on 2025-11-11 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contacto', models.EmailField(max_length=254)),
                ('nombre_contacto', models.CharField(blank=True, max_length=120)),
                ('direccion_envio', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('total_clp', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=200)),
                ('precio_unitario', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.order')),
            ],
            options={
                'indexes': [models.Index(fields=['sku'], name='ventas_orde_sku_4fab3c_idx')],
            },
        ),
    ]
